import Sidebar from '@/components/Sidebar'
import Head from 'next/head'
import Header from '../components/Header'
import Topcards from '@/components/Topcards'
import Barchar from '@/components/Barchar'
import Recentorder from '@/components/Recentorder'



export default function Home() {
  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-300 min-h-screen">
        <Header/>
        <Topcards/>
        <div className='m-[2rem] flex lg:flex-row flex-col justify-between'>
        <Barchar/>
        <Recentorder/>
      
        </div>
        
      
      </main>
    </>
  )
}
